### ISSUE TITLE
Stream Job run logs in real time

### ISSUE THREAD

**Issue by tallysmartins** [elixir-bench/elixir-bench-runner#13]
They are currently sent to the api only after the job finished

**Comment by PragTob** [comment]
I think it's ok if it only arrives after it finished right? I mean live running information like in travis is nice and cool - but I think it's a long way off for us :grin:

**Comment by tallysmartins** [comment]
Yea, maybe its not necessary to add this.  It's alright if we just give a message to the user that the job has not finished yet.
